server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true
spring:
  application:
    name: feign-client
  zipkin:
    base-url: http://localhost:8093
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream