spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/charmerares/Developtool.git
        #native:
          #search-locations: classpath:/shared
          search-paths: config
          #skip-ssl-validation: true
          username: charmerares
          password: jk00371314
          default-label: main


  application:
    name: config-server
server:
  port: 8091
#profiles:
management:
  endpoints:
    web:
      exposure:
        include: '*'
# active: native