server:
  port: 8085
spring:
  application:
    name: ribbon-client
eureka:
  client:
    service-url:
      defaultZone: http://node1:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
