server:
  port: 8090
spring:
  application:
    name: turble-client
eureka:
  client:
    service-url:
      defaultZone: http://node1:8081/eureka/
turbine:
  aggregator:
    cluster-config: default
  app-config: feign-client, ribbon-client
  cluster-name-expression: new String("default")
management:
  endpoints:
    web:
      exposure:
        include: turbine.stream
